#!/bin/bash

OCP_LATEST_VERSION=$(curl -s ${OCP_BASEURL}/release.txt | grep 'Version: ' | awk '{print $2}')

echo "Downloading openshift-install cli"
if [ ! -f ${OCP_USER_PATH}/openshift-client-linux-${OCP_LATEST_VERSION}.tar.gz ]
then
    curl -s ${OCP_BASEURL}/openshift-client-linux-${OCP_LATEST_VERSION}.tar.gz | tar -xzf - -C ${OCP_USER_PATH} oc kubectl
    curl -s ${OCP_BASEURL}/openshift-install-linux-${OCP_LATEST_VERSION}.tar.gz | tar -xzf - -C ${OCP_USER_PATH} openshift-install
fi

echo "Creating install-config.yaml"
if [ ! -f ${OCP_USER_PATH}/install-config.yaml ]
then
    ansible-playbook ${OCP_USER_PATH}/ocp-playbook.yaml
fi

echo "Preparing the install environments"

echo "Generating Manisfests files"
${OCP_USER_PATH}/openshift-install create manifests --dir=${OCP_USER_PATH}
sed -i 's/mastersSchedulable: true/mastersSchedulable: false/g' ${OCP_USER_PATH}/manifests/cluster-scheduler-02-config.yml

echo "Generating Ignitions files"
${OCP_USER_PATH}/openshift-install create ignition-configs --dir=${OCP_USER_PATH}

echo "Secondary Ignition config file for your bootstrap node to your computer"

cat <<EOF > ${OCP_USER_PATH}/ignition
{
  "ignition": {
    "config": {
      "append": [
        {
          "source": "http://${OCP_BOOTSTRAP_URL}/ocp/ignition/bootstrap.ign",
          "verification": {}
        }
      ]
    },
    "timeouts": {},
    "version": "2.1.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {},
  "systemd": {}
}
EOF

#cp -rv ${OCP_USER_PATH}/installers/bootstrap.ign ${OCP_USER_PATH}/installers/append-bootstrap.ign

echo "Generating files in base64"

cd ${OCP_USER_PATH}/ignition
for i in append-bootstrap master worker
do
    base64 -w0 < $i.ign > $i.64
done

# base64 -w0 ${OCP_USER_PATH}/installers/master.ign > ${OCP_USER_PATH}/installers/master.64
# base64 -w0 ${OCP_USER_PATH}/installers/worker.ign > ${OCP_USER_PATH}/installers/worker.64
# base64 -w0 ${OCP_USER_PATH}/installers/append-bootstrap.ign > ${OCP_USER_PATH}/installers/append-bootstrap.64

echo "Downloading RHCOS to TIER ${TIER}"
if [ ${TIER} == "vsphere" ]
then
    cd ${OCP_USER_PATH}/installers/
    wget ${RHCOS_PACKAGES}/rhcos-4.3.0-x86_64-vmware.ova
fi