## Generate Ignations Files

#### Generating Install Files

<1> The base domain of the cluster. All DNS records must be sub-domains of this base and include the cluster name.
<2> The cluster name that you specified in your DNS records.
<3> The fully-qualified host name or IP address of the vCenter server.
<4> vCenter credentials. This user must have at least the roles and privileges that are required for [dynamic persistent volume provisioning](https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html) in vSphere.
<5> The vSphere Datacenter.
<6> Default Datastore to use.
<7> Pull secret obtained in cloud.redhat.com.
<8> The public portion of the default SSH key for the core user in Red Hat Enterprise Linux CoreOS (RHCOS).

#### Set up your local environment 
----
$ cd $HOME
$ mkdir -p $HOME/ocp-installer/sharedfolder/
$ chmod 777 $HOME/ocp-installer/sharedfolder/
$ cd $HOME/ocp-installer/sharedfolder/
$ git clone https://github.com/jonascavalcantineto/openshift-bastion.git
$ cd $HOME/ocp-installer/sharedfolder/openshift-bastion
----

#### Setting the varibles in the **main-plybook.yaml** file. 

**OCP_VERSION**: Openshift versions | ex.: 3.11 , 4(Get the last Openshift version).

**BASE_DOMAIN**: Base domain of company | ex.: mycompany.com.

**OCP_BOOTSTRAP_IGN_DNSNAME**: Bastion DNS name | ex.: bastion.mycompany.com

**WORKERS_REPLICS**: Amount replics of workers node.

**MASTER_REPLICS**: Amount replics of master node (Control Plane).

**CLUSTER_NAME**: Cluster name of the Openshift.

**TIER**: Environments released: vSphere.

**VCENTER_DNS**: DNS name of the vCenter Server | ex.: vcenter.example.com.

**VCENTER_USER**: Admin user  of the VMWare environment.

**VCENTER_PASS**: Admin password of the VMWare environment.

**VCENTER_STORAGE**: Data Storage of the VMWare where will be install the components Openshift within VMWare enviroment. Default is "datastorage".

**PULL_SECRET**: You can download your PULL Secret on link:https://cloud.redhat.com/openshift/install/vsphere/user-provisioned[Red Hat Openshift Install]

#### Creating the Kubernetes manifest and Ignition config files

<1> Ansible client

----
$ cd $HOME/ocp-installer/sharedfolder/openshift-bastion

$ ansible-playbook main-playbook.yaml

$ docker-compose up -d --build

$ docker container exec -it openshift-container bash
----

[NOTE]
RHCOS OVA will be in the **$HOME/ocp-installer/sharedfolder/** of you local machine with name **rhcos-x86_64-vmware.ova**

The RHCOS images might not change with every release of OpenShift Container Platform. You must download an image with the highest version that is less than or equal to the OpenShift Container Platform version that you install. Use the image version that matches your OpenShift Container Platform version if it is available.

#### Let's confirm that webserver is hosting the bootstrap ignition file:
----
curl http://<OCP_BOOTSTRAP_IGN_DNSNAME>/ocp$GUID/ignition/
----

#### Generated configurations files on your localpath"
----
Configurations Files: $HOME/ocp-installer/sharedfolder/"

URL to access ignation and RHCOS OVA: http://${OCP_BOOTSTRAP_IGN_DNSNAME}/ocp${OCP_USERID}/ignition/"

OCP access files: $HOME/ocp-installer/sharedfolder/auth"
----

