FROM centos:8

RUN yum update -y && yum install -y \
		epel-release

RUN yum update -y && yum install -y \
        vim \
        curl \
        openssh \
        wget \
        httpd \
        sudo \
		supervisor

#OCP variables
ENV OCP_VERSION="4.3"
ENV OCP_BASEURL="https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest"
ENV OCP_BOOTSTRAP_URL="bootstrap.mycompany.com"

ENV RHCOS_PACKAGES="https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/${OCP_VERSION}/latest"

ENV OCP_USERID={{ OCP_USERID }} 
ENV OCP_USER_PATH="/home/ocp${OCP_USERID}"

#Cluster variables
ENV BASE_DOMAIN=mycompany.com
ENV WORKERS_REPLICS="4"
ENV MASTER_REPLICS="3"
ENV CLUSTER_NAME="cluster-01"
ENV CLUSTER_CIDR="10.254.0.0/16"
ENV CLUSTER_SERVICE_NETWORK="172.30.0.0/16"
ENV TIER="vsphere"
ENV PULL_SECRET=""
ENV OCP_SSH_KEY="cat ~/.ssh/id_rsa.pub"

#vSphere variables
ENV VCENTER_SERVER="vcenter.local"
ENV VCENTER_USER=""
ENV VCENTER_PASS=""
ENV VCENTER_DC="datacenter"
ENV VCENTER_DS="datastore"

# Add none root user
RUN useradd ocp${OCP_USERID}

RUN set -ex \
    && echo "ocp${OCP_USERID} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/user \
    && chmod 0440 /etc/sudoers.d/user

ADD confs/supervisord.conf /etc/supervisord.conf

ADD confs/install-config.yaml ${OCP_USER_PATH}/install-config.yaml

ADD confs/ssh/id_rsa ${OCP_USER_PATH}/.ssh/id_rsa
ADD confs/ssh/id_rsa.pub ${OCP_USER_PATH}/.ssh/id_rsa.pub

RUN chown ocp${OCP_USERID} -R ${OCP_USER_PATH}/*
RUN chown ocp${OCP_USERID} /var/www/html -R

ADD confs/init-ocp-configd /init-ocp-configd
RUN chmod +x /init-ocp-configd && /usr/bin/chown ocp${OCP_USERID} /init-ocp-configd

ADD confs/init-httpd /init-httpd 
RUN chmod +x /init-httpd 

#&& /usr/bin/chown ocp${OCP_USERID} /init-httpd
RUN set -ex \
         && /usr/bin/chown ocp${OCP_USERID}:ocp${OCP_USERID} /run /var/log/httpd/\
         && sed -i "s/User apache/User ocp${OCP_USERID}/" /etc/httpd/conf/httpd.conf \
         && sed -i "s/Group apache/Group ocp${OCP_USERID}/" /etc/httpd/conf/httpd.conf

ADD confs/start.sh /start.sh
RUN chmod +x /start.sh

VOLUME [ "${OCP_USER_PATH}" ]
USER ocp${OCP_USERID}
WORKDIR ${OCP_USER_PATH}

CMD ["/start.sh"]